import type { Metadata } from "next";
import "@/styles/globals.css";
import { CustomTrigger } from "@/components/custom-trigger";
import { SettingsBar } from "@/components/settings-bar";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider defaultOpen={false}>
      <AppSidebar />

      <main className="h-screen min-h-screen w-full overflow-y-hidden">
        <CustomTrigger />
        <SettingsBar />
        {children}
      </main>
    </SidebarProvider>
  );
}
