import "@/styles/globals.css";
import { Suspense } from "react";

export const metadata = {
  title: "Auth",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <Suspense fallback={<div />}>{children}</Suspense>;
}
